# backend/data.py

training_data = [
    # General greetings/questions
    {"text": "Hi", "intent": "greet"},
    {"text": "Hello", "intent": "greet"},
    {"text": "Hey there", "intent": "greet"},
    {"text": "Good morning", "intent": "greet"},
    {"text": "Good evening", "intent": "greet"},
    {"text": "Greetings", "intent": "greet"},
    {"text": "How can I help you?", "intent": "general_inquiry"}, # Bot speaking to user
    {"text": "Tell me about careers", "intent": "general_inquiry"},
    {"text": "What do you do?", "intent": "general_inquiry"},
    {"text": "How can you help?", "intent": "general_inquiry"},
    {"text": "I'm looking for career advice", "intent": "general_inquiry"},
    {"text": "Help me find a career path", "intent": "general_inquiry"},
    {"text": "What career options are there?", "intent": "general_inquiry"},
    {"text": "Show me career fields", "intent": "general_inquiry"},
    {"text": "Can you recommend a career?", "intent": "general_inquiry"},
    {"text": "What careers are available?", "intent": "general_inquiry"},
    {"text": "Guide me on career choices", "intent": "general_inquiry"},
    {"text": "Explore jobs", "intent": "general_inquiry"},
    {"text": "What career should I choose?", "intent": "general_inquiry"},


    # Field selection (added more text variations)
    {"text": "I'm interested in science", "intent": "select_field_science"},
    {"text": "Arts careers", "intent": "select_field_arts"},
    {"text": "Tell me about business", "intent": "select_field_business"},
    {"text": "Engineering field", "intent": "select_field_engineering"},
    {"text": "Healthcare jobs", "intent": "select_field_healthcare"},
    {"text": "Law related careers", "intent": "select_field_law"},
    {"text": "Education sector", "intent": "select_field_education"},
    {"text": "Environment careers", "intent": "select_field_environment"},
    {"text": "Sports related careers", "intent": "select_field_sports"},
    {"text": "Social sciences field", "intent": "select_field_social sciences"}, # Must match backend key
    {"text": "I like science", "intent": "select_field_science"},
    {"text": "Business options", "intent": "select_field_business"},
    {"text": "Show me engineering careers", "intent": "select_field_engineering"},
    {"text": "What about the arts?", "intent": "select_field_arts"},
    {"text": "Careers in medicine", "intent": "select_field_healthcare"},
    {"text": "Jobs in education", "intent": "select_field_education"},
    {"text": "Environmental jobs", "intent": "select_field_environment"},
    {"text": "What about sports?", "intent": "select_field_sports"},
    {"text": "I want to work in law", "intent": "select_field_law"},
    {"text": "Tell me about social sciences", "intent": "select_field_social sciences"},
    {"text": "Science jobs please", "intent": "select_field_science"},
    {"text": "I'm keen on business", "intent": "select_field_business"},

    # Questions about skills (more generic, relies on role extraction in app.py)
    {"text": "What skills do I need?", "intent": "get_skills"},
    {"text": "Required skills", "intent": "get_skills"},
    {"text": "What are the skills for this?", "intent": "get_skills"},
    {"text": "Skills for a role", "intent": "get_skills"},
    {"text": "What should I learn?", "intent": "get_skills"},
    {"text": "What abilities are required?", "intent": "get_skills"},
    {"text": "Key competencies?", "intent": "get_skills"},
    {"text": "What proficiencies are good?", "intent": "get_skills"},
    {"text": "Essential skills?", "intent": "get_skills"},
    {"text": "What qualities should one have?", "intent": "get_skills"},
    {"text": "Abilities for a position?", "intent": "get_skills"},
    {"text": "Expertise required?", "intent": "get_skills"},
    {"text": "Tell me about skills.", "intent": "get_skills"},
    {"text": "What are the necessary skills?", "intent": "get_skills"},
    {"text": "What skills are important?", "intent": "get_skills"},


    # Questions about daily tasks/day in life (more generic)
    {"text": "What does a day look like?", "intent": "get_daily_tasks"},
    {"text": "Daily routine", "intent": "get_daily_tasks"},
    {"text": "A day in the life", "intent": "get_daily_tasks"},
    {"text": "What does one do daily?", "intent": "get_daily_tasks"},
    {"text": "Tell me about the everyday work.", "intent": "get_daily_tasks"},
    {"text": "What are the typical responsibilities?", "intent": "get_daily_tasks"},
    {"text": "Describe the routine.", "intent": "get_daily_tasks"},
    {"text": "What does a typical day involve?", "intent": "get_daily_tasks"},
    {"text": "Daily activities?", "intent": "get_daily_tasks"},
    {"text": "What's the typical workday?", "intent": "get_daily_tasks"},
    {"text": "Routine?", "intent": "get_daily_tasks"},
    {"text": "What does a person in this job do?", "intent": "get_daily_tasks"},

    # Questions about how to get into a role (more generic)
    {"text": "How to get into it?", "intent": "get_how_to_get_into"},
    {"text": "How can I become one?", "intent": "get_how_to_get_into"},
    {"text": "Steps to become?", "intent": "get_how_to_get_into"},
    {"text": "Path to being?", "intent": "get_how_to_get_into"},
    {"text": "How do I start a career?", "intent": "get_how_to_get_into"},
    {"text": "What's the career path?", "intent": "get_how_to_get_into"},
    {"text": "Guidance on becoming?", "intent": "get_how_to_get_into"},
    {"text": "How can I get into this field?", "intent": "get_how_to_get_into"},
    {"text": "What is the way to become?", "intent": "get_how_to_get_into"},
    {"text": "How to pursue a career?", "intent": "get_how_to_get_into"},
    {"text": "Steps to become?", "intent": "get_how_to_get_into"},
    {"text": "What do I need to do to become?", "intent": "get_how_to_get_into"},


    # Questions about salary (more generic)
    {"text": "What is the salary?", "intent": "get_salary"},
    {"text": "Salary of a position", "intent": "get_salary"},
    {"text": "How much does one earn?", "intent": "get_salary"},
    {"text": "Earnings?", "intent": "get_salary"},
    {"text": "Expected salary?", "intent": "get_salary"},
    {"text": "What's the earning potential?", "intent": "get_salary"},
    {"text": "Average income?", "intent": "get_salary"},
    {"text": "Pay for a role", "intent": "get_salary"},
    {"text": "How much does one get paid?", "intent": "get_salary"},
    {"text": "What can I expect to earn?", "intent": "get_salary"},
    {"text": "How much does a person make?", "intent": "get_salary"},
    {"text": "Remuneration?", "intent": "get_salary"},
    {"text": "Income details?", "intent": "get_salary"},
    {"text": "How much money?", "intent": "get_salary"},
    {"text": "Show me salary data.", "intent": "get_salary"},


    # Questions about education needed (more generic)
    {"text": "What education is needed?", "intent": "get_education_needed"},
    {"text": "Education for a role", "intent": "get_education_needed"},
    {"text": "Required degrees?", "intent": "get_education_needed"},
    {"text": "What do I need to study?", "intent": "get_education_needed"},
    {"text": "What qualifications are necessary?", "intent": "get_education_needed"},
    {"text": "Degree requirements?", "intent": "get_education_needed"},
    {"text": "What academic path leads?", "intent": "get_education_needed"},
    {"text": "Educational background?", "intent": "get_education_needed"},
    {"text": "What kind of schooling is needed?", "intent": "get_education_needed"},
    {"text": "Study required?", "intent": "get_education_needed"},
    {"text": "What should I major in?", "intent": "get_education_needed"},
    {"text": "Courses required?", "intent": "get_education_needed"},

    # Questions about job outlook (more generic)
    {"text": "Job outlook?", "intent": "get_job_outlook"},
    {"text": "Future for this role", "intent": "get_job_outlook"},
    {"text": "Is this in demand?", "intent": "get_job_outlook"},
    {"text": "Job prospects?", "intent": "get_job_outlook"},
    {"text": "What is the demand?", "intent": "get_job_outlook"},
    {"text": "Future of the profession?", "intent": "get_job_outlook"},
    {"text": "Is this a growing field?", "intent": "get_job_outlook"},
    {"text": "What is the career future?", "intent": "get_job_outlook"},
    {"text": "Are they in demand?", "intent": "get_job_outlook"},
    {"text": "What's the market for this?", "intent": "get_job_outlook"},
    {"text": "Employment prospects?", "intent": "get_job_outlook"},
    {"text": "Growth prospects?", "intent": "get_job_outlook"},
    {"text": "How is the job market?", "intent": "get_job_outlook"},


    # Catch-all/none of the above
    {"text": "I don't understand", "intent": "fallback"},
    {"text": "Can you repeat that?", "intent": "fallback"},
    {"text": "Tell me something else", "intent": "fallback"},
    {"text": "Random text here", "intent": "fallback"},
    {"text": "What is this?", "intent": "fallback"},
    {"text": "Tell me a joke", "intent": "fallback"},
    {"text": "What's the weather like today?", "intent": "fallback"},
    {"text": "How old are you?", "intent": "fallback"},
    {"text": "Can you define democracy?", "intent": "fallback"},
    {"text": "Show me a picture of a cat.", "intent": "fallback"},
    {"text": "I'm feeling down", "intent": "fallback"},
    {"text": "Can you sing?", "intent": "fallback"},
    {"text": "Where are you from?", "intent": "fallback"},
    {"text": "How are you doing?", "intent": "fallback"},
    {"text": "What's up?", "intent": "fallback"},
    {"text": "I want to chat", "intent": "fallback"},
    {"text": "Tell me a story", "intent": "fallback"},
]